version: "0.5"

processes:
  server:
    command: pnpm dev
    working_dir: ./server
    availability:
      restart: on_failure
      max_restarts: 5

  app:
    command: pnpm dev
    working_dir: ./app
    availability:
      restart: on_failure
      max_restarts: 5
